--[[
    GD50
    Space Invaders

    constants

    Distribution Code

    Constants used globally in our application.
]]

VIRTUAL_WIDTH = 224
VIRTUAL_HEIGHT = 256

WINDOW_WIDTH = VIRTUAL_WIDTH * 4
WINDOW_HEIGHT = VIRTUAL_HEIGHT * 4

PLAYER_WIDTH = 16
PLAYER_HEIGHT = 16
PLAYER_SPEED = 120

ALIEN_WIDTH = 16
ALIEN_HEIGHT = 16
SHOOT_CHANCE = 1000
ALIEN_DX = 16
ALIEN_DOWNSHIFT = 8

PROJECTILE_WIDTH = 1
PROJECTILE_HEIGHT = 8
PROJECTILE_SPEED = 200

BOSS_PROJECTILE_WIDTH = 8

SECONDS_BETWEEN_LEVELS = 4
